name: Schedule Debug

on:
  schedule:
    - cron: '2,7,12,17,22,27,32,37,42,47,52,57 * * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Debug
        run: |
          echo "=============================="
          echo "WORKFLOW SCHEDULED TEST"
          echo "=============================="
          echo "UTC: $(date -u)"
          echo "IST: $(TZ='Asia/Kolkata' date)"
          echo "Event: ${{ github.event_name }}"
          echo "Schedule: ${{ github.event.schedule }}"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
