name: Old Schedule Test

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "UTC: $(date -u)"
          echo "IST: $(TZ='Asia/Kolkata' date)"
          echo "Event: ${{ github.event_name }}"
